### ISSUE TITLE
Interactive tab selection when no arguments are provided

### ISSUE THREAD

**Issue by austinjones** [austinjones/tab-rs#1]

**Comment by Jacobious52** [comment]
This would be a great feature to have. Perhaps something with fuzzy search like [fzf](https://github.com/junegunn/fzf) or [skim](https://github.com/lotabout/skim) would work well, if not overkill.

**Comment by austinjones** [comment]
@Jacobious52 Yep!  That's exactly what I was thinking.  Plus I can search the workspace / repo docstrings as well.

**Comment by Jacobious52** [comment]
Nice! For fun/learning I did a super rough and buggy proof of concept in a fork in the `fuzzy-poc` [branch here](https://github.com/austinjones/tab-rs/compare/main...Jacobious52:fuzzy-poc) . I used `skim` since it has a rust library but matches `fzf` in functionality/quality, I think `skim` is quiet heavy on dependences though, so not sure if you wanna go that route. UX wise it feels good though. Keen to see what you come up with!

![image](https://user-images.githubusercontent.com/12645162/95430298-51adfa00-0997-11eb-845c-e4fd9476fa8d.png)

**Comment by austinjones** [comment]
Woah!  _Super cool._

Yeah, Rayon & Crossbeam.  They make sense - it's based on blocking I/O.  I also found https://github.com/jhbabon/scout which runs on smol/asyncstd.

I like the fzf search syntax.  It's be nice if I could support that.

I'll probably get back to this in a week or so once 0.4.0 is out.  This is gonna be so cool!

**Comment by austinjones** [comment]
@Jacobious52 I just merged initial support for this in #195.  I used the [fuzzy-matcher](https://crates.io/crates/fuzzy-matcher) crate that Skim uses, so the matching behavior should be similar.

I wrote my [own UI](https://github.com/austinjones/tab-rs/blob/main/tab-command/src/service/terminal/fuzzy.rs) because I wanted it to be based on async and crossterm.  Skim wasn't async, and scout was /dev/tty based (which would prevent future windows support).  Plus it supports tab-aware search & output formatting.

![no-filter](https://user-images.githubusercontent.com/2111479/95888337-f725ec80-0d4e-11eb-9212-09b231ce3d30.png)

![filter](https://user-images.githubusercontent.com/2111479/95888345-fa20dd00-0d4e-11eb-8a99-5795f578d8d1.png)

I still have a few things to add:
- Handle terminal size (truncate width & height), and redraw on resizes
- Add the 'Matched/Total' counts

**Comment by Jacobious52** [comment]
Wow! Looks awesome! Combining fuzzy-matcher` with `crossterm` looks like a great choice 👍  Can't wait to try it out.

**Comment by austinjones** [comment]
I think this is stable on the main branch, so I'm closing this.
