### ISSUE TITLE
Rendering issue with neovim

### ISSUE THREAD

**Issue by kyle-mccarthy** [austinjones/tab-rs#226]
When neovim is used inside a "tab" it leads to layout and navigation issues inside vim. I've attached a gif to help explain the behavior I'm seeing.

**Environment:**
- tab 0.5.0
- NVIM v0.5.0-nightly-36-g186ba3b68
- alacritty 0.6.0-dev (5986842)
- macos 10.15.7

![2020-11-03 15 40 06](https://user-images.githubusercontent.com/7758522/98044248-32ff1f80-1dec-11eb-9440-9f191fe69163.gif)

As a side note, I really like using this so far. It seems like a great idea and hope you continue to pursue it!

**Comment by austinjones** [comment]
Hi Kyle,
Thanks for the report!  The gif is really helpful.

I'll put out a patch release once I figure out what is going on here.

**Comment by ArticOceanWater** [comment]
Hey ,I just wanted to tell that I've been experiencing a similar issue with an another editor called kakoune.
Do you need a recording of the bug?

**Environment:**
- tab [0.5.0]
- kakoune [2020.09.01]
- Arch Linux [kernel: 5.9.2-zen1-1-zen]
- alacritty-ligatures-git [0.6.0]

**Comment by austinjones** [comment]
Hi @kyle-mccarthy and @ArticOceanWater - I think I figured out what is happening here.  I'm sorry it took a while, this one was tough to crack.

I'm working on a fix, and I'll let you know once I've published a release!

**Comment by austinjones** [comment]
@kyle-mccarthy and @ArticOceanWater, thanks again for the great bug report!  I just published [v0.5.1](https://github.com/austinjones/tab-rs/releases/tag/v0.5.1) with several fixes.  There were a few issues:
- The command client was printing some '\r' characters that it should not have.  That was causing the corruption with text appearing before the line numbers.
- The max size of the scrollback buffer was way too small, which caused all kinds of havoc when resuming sessions (particularly due to the cursor location state).  I've increased to a max of 128MB per tab, which is enough to scan through reasonably sized files 5k+ times.

I also noticed another bug (I am still working on it) where tab doesn't properly send a 'resize' request when reconnected via retask (e.g. typing `tab my-previous-session` while within an active session): #230 

Feel free to re-open this if something is still broken.
