### ISSUE TITLE
Create new tabs in the fuzzy finder

### ISSUE THREAD

**Issue by nebbishhacker** [austinjones/tab-rs#232]
I would like to be able to create new tabs in the fuzzy finder.

Perhaps a "new tab" option could be added to the bottom of the list of tabs. If there are no matches it would get selected by default, and if there are partial matches you would still be able to create a new tab named by manually selecting the option. Something like this:
```
❯ foo
  1/5
❯ foobar/
❯ foo/ (new tab)
```

**Comment by austinjones** [comment]
Yeah, I've been thinking about this!  I like the idea of having it be the last option.  Then once you've typed your new tab name, it likely won't match anything else.

**Comment by krgn** [comment]
Yes, this is a really good idea! It would be nice to set my "terminal" command to something like `termite -e tab` to either connect to an exisiting session, or, alternatively, start a new sub-tab for a project. I was looking around in the code, but where would be a good point to start reading? I was thinking, it could be an alternative action to `SelectInteractive` called `SelectOrCreateInteractive` for starters.

**Comment by austinjones** [comment]
Hi @krgn,
I think this could be the default behavior for the fuzzy finder.  The current behavior on 'no match' is that it simply quits, which isn't so helpful.

The fuzzy finder UI code is here: https://github.com/austinjones/tab-rs/blob/main/tab-command/src/service/terminal/fuzzy.rs

As for implementation, I think it could be as simple as constructing a new tab entry with the query as the tab name, and 'new tab' as the docstring: https://github.com/austinjones/tab-rs/blob/main/tab-command/src/service/terminal/fuzzy.rs#L313

Also, if you want to play around with it I have a few tips for developing locally:
- You'll need to uncomment the cargo patch for tab-command, so that that the `tab` build includes your local changes.  https://github.com/austinjones/tab-rs/blob/main/Cargo.toml#L17
- You can use `scripts/run.sh` to run tab in debug mode.  If the daemon isn't running, it'll relaunch the daemon in debug mode too.
