### ISSUE TITLE
Splits/Panes

### ISSUE THREAD

**Issue by jrop** [austinjones/tab-rs#261]
`tab` elegantly handles Tmux's most useful feature: multiple windows.  However, I frequently make use of splits/panes in Tmux as well.  Are there any plans for `tab` to support splits/panes?

**Comment by austinjones** [comment]
It's not possible with tab's architecture.  It's an intentional design choice.  One of the reasons is that tab supports native scrollback and search in your terminal emulator.  This makes dealing with local servers/log output much easier.  But it means that I can't support split panes - as tab would have to replace all that functionality with selection, scrolling, search, etc.

Tab tries to make up for it by making it really easy to rapidly switch back and forth between sessions, with the fuzzy finder, autocomplete, etc.

**Comment by alexherbo2** [comment]
[mtm] runs very well in tab.

[mtm]: https://github.com/deadpixi/mtm

**Comment by alexherbo2** [comment]
Just found about [Zellij] too, which can be run from tab.

[Zellij]: https://zellij.dev
