### ISSUE TITLE
Re-home session under tab?

### ISSUE THREAD

**Issue by kbd** [austinjones/tab-rs#312]
A lot of times I'll start a new terminal session with `⌘n` to open a new iterm window, and only later realize I should have started my session under `tab` so I'm able to detatch from it.

There are programs like [`reptyr`](https://github.com/nelhage/reptyr) that try to solve this in the general case. It sounds like a really hairy problem (eg. `reptyr` doesn't support macOS atm), so it's probably out of scope for `tab`.

Still, it'd be nice if `tab` could take an existing terminal session and turn it into a "tab".

**Comment by austinjones** [comment]
Hmm.  This sounds very hard :D

Particularly so because I need the I/O to be Tokio-compatible (for async).  Launching the PTY process and driving the reactor takes some care.

Also, I don't think it would work with scrollback.  That could cause ANSI issues - as many terminal state escape sequences needs to be repeated when reconnecting.

I don't see any way to implement this without a lot of bugs.
